//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalOne.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaturalOne.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilities.
        /// </summary>
        public static string Builder_Abilities_StepTitle {
            get {
                return ResourceManager.GetString("Builder.Abilities.StepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Builder_Class_StepTitle {
            get {
                return ResourceManager.GetString("Builder.Class.StepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string Builder_Race_StepTitle {
            get {
                return ResourceManager.GetString("Builder.Race.StepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        public static string Enums_Ability_Charisma {
            get {
                return ResourceManager.GetString("Enums.Ability.Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string Enums_Ability_Constitution {
            get {
                return ResourceManager.GetString("Enums.Ability.Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        public static string Enums_Ability_Dexterity {
            get {
                return ResourceManager.GetString("Enums.Ability.Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string Enums_Ability_Intelligence {
            get {
                return ResourceManager.GetString("Enums.Ability.Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Enums_Ability_Strength {
            get {
                return ResourceManager.GetString("Enums.Ability.Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        public static string Enums_Ability_Wisdom {
            get {
                return ResourceManager.GetString("Enums.Ability.Wisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonborn.
        /// </summary>
        public static string Races_Dragonborn_Name {
            get {
                return ResourceManager.GetString("Races.Dragonborn.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        public static string Races_Dwarf_Name {
            get {
                return ResourceManager.GetString("Races.Dwarf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf.
        /// </summary>
        public static string Races_Elf_Name {
            get {
                return ResourceManager.GetString("Races.Elf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnome.
        /// </summary>
        public static string Races_Gnome_Name {
            get {
                return ResourceManager.GetString("Races.Gnome.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Elf.
        /// </summary>
        public static string Races_HalfElf_Name {
            get {
                return ResourceManager.GetString("Races.HalfElf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfling.
        /// </summary>
        public static string Races_Halfling_Name {
            get {
                return ResourceManager.GetString("Races.Halfling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Orc.
        /// </summary>
        public static string Races_HalfOrc_Name {
            get {
                return ResourceManager.GetString("Races.HalfOrc.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Elf.
        /// </summary>
        public static string Races_HighElf_Name {
            get {
                return ResourceManager.GetString("Races.HighElf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Dwarf.
        /// </summary>
        public static string Races_HillDwarf_Name {
            get {
                return ResourceManager.GetString("Races.HillDwarf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string Races_Human_Name {
            get {
                return ResourceManager.GetString("Races.Human.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightfoot Halfling.
        /// </summary>
        public static string Races_LightfootHalfling_Name {
            get {
                return ResourceManager.GetString("Races.LightfootHalfling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Dwarf.
        /// </summary>
        public static string Races_MountainDwarf_Name {
            get {
                return ResourceManager.GetString("Races.MountainDwarf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Gnome.
        /// </summary>
        public static string Races_RockGnome_Name {
            get {
                return ResourceManager.GetString("Races.RockGnome.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stout Halfling.
        /// </summary>
        public static string Races_StoutHalfling_Name {
            get {
                return ResourceManager.GetString("Races.StoutHalfling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiefling.
        /// </summary>
        public static string Races_Tiefling_Name {
            get {
                return ResourceManager.GetString("Races.Tiefling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant Human.
        /// </summary>
        public static string Races_VariantHuman_Name {
            get {
                return ResourceManager.GetString("Races.VariantHuman.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Elf.
        /// </summary>
        public static string Races_WoodElf_Name {
            get {
                return ResourceManager.GetString("Races.WoodElf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Strength score increases by 2, and your Charisma score increases by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_Dragonborn {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.Dragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Constitution score increases by 2..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_Dwarf {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Dexterity score increases by 2..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_Elf {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Intelligence score increases by 2..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_Gnome {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.Gnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Charisma score increases by 2, and two other ability scores of your choice increase by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_HalfElf {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.HalfElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Dexterity score increases by 2..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_Halfling {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.Halfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Strength score increases by 2, and your Constitution score increases by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_HalfOrc {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.HalfOrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Intelligence score increases by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_HighElf {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.HighElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Wisdom score increases by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_HillDwarf {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.HillDwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ability scores each increase by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_Human {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Charisma score increases by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_LightfootHalfling {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.LightfootHalfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Strength score increases by 2..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_MountainDwarf {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.MountainDwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Constitution score increases by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_RockGnome {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.RockGnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Constitution score increases by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_StoutHalfling {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.StoutHalfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Intelligence score increases by 1, and your Charisma score increases by 2..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_Tiefling {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.Tiefling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two different ability scores of your choice increase by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_VariantHuman {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.VariantHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Wisdom score increases by 1..
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Description_WoodElf {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Description.WoodElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Score Increase.
        /// </summary>
        public static string Traits_AbilityScoreIncrease_Name {
            get {
                return ResourceManager.GetString("Traits.AbilityScoreIncrease.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Traits_Age_Name {
            get {
                return ResourceManager.GetString("Traits.Age.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string Traits_Alignment_Name {
            get {
                return ResourceManager.GetString("Traits.Alignment.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Traits_Languages_Name {
            get {
                return ResourceManager.GetString("Traits.Languages.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Traits_Size_Name {
            get {
                return ResourceManager.GetString("Traits.Size.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your base walking speed is {0} feet..
        /// </summary>
        public static string Traits_Speed_Description {
            get {
                return ResourceManager.GetString("Traits.Speed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your base walking speed is 25 feet. Your speed is not reduced by wearing heavy armor..
        /// </summary>
        public static string Traits_Speed_Description_Dwarf {
            get {
                return ResourceManager.GetString("Traits.Speed.Description.Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your base walking speed increases to 35 feet..
        /// </summary>
        public static string Traits_Speed_Description_WoodElf {
            get {
                return ResourceManager.GetString("Traits.Speed.Description.WoodElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Traits_Speed_Name {
            get {
                return ResourceManager.GetString("Traits.Speed.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet o f Foot.
        /// </summary>
        public static string Traits_Speed_Name_WoodElf {
            get {
                return ResourceManager.GetString("Traits.Speed.Name.WoodElf", resourceCulture);
            }
        }
    }
}
