//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalOne.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaturalOne.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Builder_Class_StepTitle {
            get {
                return ResourceManager.GetString("Builder.Class.StepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string Builder_Race_StepTitle {
            get {
                return ResourceManager.GetString("Builder.Race.StepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonborn.
        /// </summary>
        public static string Races_Dragonborn_Name {
            get {
                return ResourceManager.GetString("Races.Dragonborn.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        public static string Races_Dwarf_Name {
            get {
                return ResourceManager.GetString("Races.Dwarf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf.
        /// </summary>
        public static string Races_Elf_Name {
            get {
                return ResourceManager.GetString("Races.Elf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnome.
        /// </summary>
        public static string Races_Gnome_Name {
            get {
                return ResourceManager.GetString("Races.Gnome.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Elf.
        /// </summary>
        public static string Races_HalfElf_Name {
            get {
                return ResourceManager.GetString("Races.HalfElf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfling.
        /// </summary>
        public static string Races_Halfling_Name {
            get {
                return ResourceManager.GetString("Races.Halfling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Orc.
        /// </summary>
        public static string Races_HalfOrc_Name {
            get {
                return ResourceManager.GetString("Races.HalfOrc.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Elf.
        /// </summary>
        public static string Races_HighElf_Name {
            get {
                return ResourceManager.GetString("Races.HighElf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Dwarf.
        /// </summary>
        public static string Races_HillDwarf_Name {
            get {
                return ResourceManager.GetString("Races.HillDwarf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string Races_Human_Name {
            get {
                return ResourceManager.GetString("Races.Human.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightfoot Halfling.
        /// </summary>
        public static string Races_LightfootHalfling_Name {
            get {
                return ResourceManager.GetString("Races.LightfootHalfling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Dwarf.
        /// </summary>
        public static string Races_MountainDwarf_Name {
            get {
                return ResourceManager.GetString("Races.MountainDwarf.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Gnome.
        /// </summary>
        public static string Races_RockGnome_Name {
            get {
                return ResourceManager.GetString("Races.RockGnome.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stout Halfling.
        /// </summary>
        public static string Races_StoutHalfling_Name {
            get {
                return ResourceManager.GetString("Races.StoutHalfling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiefling.
        /// </summary>
        public static string Races_Tiefling_Name {
            get {
                return ResourceManager.GetString("Races.Tiefling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant Human.
        /// </summary>
        public static string Races_VariantHuman_Name {
            get {
                return ResourceManager.GetString("Races.VariantHuman.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Elf.
        /// </summary>
        public static string Races_WoodElf_Name {
            get {
                return ResourceManager.GetString("Races.WoodElf.Name", resourceCulture);
            }
        }
    }
}
